name: release
on:
  push:
    branches:
      - main

jobs:
  stable:
    uses: ./.github/workflows/release-stable.yml
    with:
      releaseScript: release 
      nodeVersion: 18
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NPM_TOKEN }}